name=ProsecCoAP
version=5.0.0
author=Pasquale Lafiosca
maintainer=Pasquale Lafiosca
sentence=CoAP client/server library for Arduino-compatible hardware.
paragraph=ProsecCoAP 🥂 is a lightweight implementation of a Constrained Application Protocol (CoAP) node, that includes client/server, request/response and the asynchronous observe pattern, enabling robust M2M communication for IoT projects.
category=Communication
url=https://github.com/decadenza/ProsecCoAP
architectures=*
