name=ProsecCoAP
version=1.0.1
author=Pasquale Lafiosca <pasquale.lafiosca@yahoo.it>
maintainer=Pasquale Lafiosca <pasquale.lafiosca@yahoo.it>
sentence=CoAP client/server library for generic Arduino hardware.
paragraph=This CoAP library supports request/response message and the observe pattern. The objective is to implement the Constrained Application Protocol (CoAP) following RFC-7252 as closely as possible.
category=Communication
url=https://github.com/decadenza/ProsecCoAP
architectures=*
