name: Documentation build and deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Permissions required for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  documentation-build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Generate Documentation
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: ./Doxyfile

      # 2. Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v6

      # 3. Upload Artifacts
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./html

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
