name: Unit tests
on: [push, pull_request, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Initialize and update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - name: Unit tests
        run: make test
