name: Unit tests
on: [push, pull_request, workflow_dispatch]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Unit tests
        run: make test
